# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    copts = [],
    deps = ["@wpilibc//:wpilibc", "@ctre_phoenix_api_cpp//:ctre_phoenix_api_cpp", ],
)