name: CI

on:
  push: {}

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: ngalaiko/bazel-action/2.1.0@master
      with:
        args: build //... --config=roborio