name: CI

on:
  push: {}

jobs:
  checks:
    name: VerifyBuild
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: InstallBazel
      run: |
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update && sudo apt install bazel
        sudo apt install bazel-2.1.0
        sudo apt install libfuse2
        curl -OL https://github.com/bazelbuild/sandboxfs/releases/download/sandboxfs-0.1.1/sandboxfs-0.1.1-20191024-linux-x86_64.tgz
        ls
        tar xzv -C /usr/local -f sandboxfs-0.1.1-20191024-linux-x86_64.tgz
    
    - name: Test
      run: |
        bazel test //... --config=roborio

    - name: Build
      run: |
        bazel build //... --config=roborio
    

