name: CI

on:
  push: {}

jobs:
  checks:
    name: VerifyBuild
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: InstallBazel
      run: |
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update && sudo apt install bazel
        sudo apt install bazel-2.1.0
        sudo apt install libfuse-dev pkg-config
        rustup update
        cargo install sandboxfs

    - name: Build
      run: |
        bazel build //... --config=roborio
    
    # - name: Test
    #   run: |
    #     bazel test //... --config=roborio


    

